services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: boxoffice_clickhouse
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "8123:8123" # HTTP interface for clickhouse-connect
      - "9000:9000" # Native interface
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  postgres:
    image: postgres:15-alpine
    container_name: boxoffice_postgres
    environment:
      POSTGRES_DB: boxoffice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  clickhouse_data:
  postgres_data: