import operator
from typing import Annotated, List, Dict, Any, Optional
from typing_extensions import TypedDict
from langchain_core.messages import BaseMessage

class AgentState(TypedDict):
    messages: Annotated[List[BaseMessage], operator.add]
    # Active user context & session tracking
    thread_id: str
    current_intent: Optional[str] # 'general_chat', 'analytics_query', 'anomaly_action'
    # Executed ClickHouse SQL & raw results
    generated_sql: Optional[str]
    query_results: Optional[List[Dict[str, Any]]]
    # Actionable decisions generated by the Action Agent
    recommended_actions: Optional[List[Dict[str, Any]]]

    reasoning_steps: Annotated[List[str], operator.add]

    # ── Agentic loop: entity resolution & self-correction ──────────────────────
    # Exact DB titles matched from user keywords (set-deduplicated)
    resolved_entities: List[str]
    # Actual ClickHouse titles fetched as grounding hints after a zero-row retry
    available_db_titles: List[str]
    # Retry loop counters & signals
    iteration_count: int       # incremented in generate_sql_node; default 0
    max_iterations: int        # hard cap; default 5
    needs_retry: bool          # conditional edge signal; default False
    # Previous SQL that returned 0 rows — fed back to the LLM on next attempt
    last_failed_sql: Optional[str]