import operator
from typing import Annotated, List, Dict, Any, Optional
from typing_extensions import TypedDict
from langchain_core.messages import BaseMessage

class AgentState(TypedDict):
    messages: Annotated[List[BaseMessage], operator.add]
    # Active user context & session tracking
    thread_id: str
    current_intent: Optional[str] # 'general_chat', 'analytics_query', 'anomaly_action'
    # Executed ClickHouse SQL & raw results
    generated_sql: Optional[str]
    query_results: Optional[List[Dict[str, Any]]]
    # Actionable decisions generated by the Action Agent
    recommended_actions: Optional[List[Dict[str, Any]]]

    reasoning_steps: Annotated[List[str], operator.add]